# Generated by Django 6.0.1 on 2026-04-19 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("merchstore", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.profile",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_image",
            field=models.ImageField(default=1, upload_to="images/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("on_sale", "On sale"),
                    ("out_of_stock", "Out of stock"),
                ],
                default="available",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("on_cart", "On cart"),
                            ("to_pay", "To Pay"),
                            ("to_ship", "To Ship"),
                            ("to_receive", "To Receive"),
                            ("delivered", "Delivered"),
                        ],
                        max_length=255,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.profile",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="merchstore.product",
                    ),
                ),
            ],
        ),
    ]
