# Generated by Django 6.0.2 on 2026-05-05 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_role'),
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='commission_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='commissions.commissiontype'),
        ),
        migrations.AddField(
            model_name='commission',
            name='maker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='commission',
            name='status',
            field=models.CharField(choices=[('A', 'Open'), ('B', 'Full')], default='A'),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('manpower_required', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('A', 'Open'), ('B', 'Full')], default='A')),
                ('commission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commissions.commission')),
            ],
            options={
                'ordering': ['status', '-manpower_required', 'role'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Pending'), ('B', 'Accepted'), ('C', 'Rejected')], default='A')),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commissions.job')),
            ],
            options={
                'ordering': ['status', '-applied_on'],
            },
        ),
    ]
