# Generated by Django 6.0.2 on 2026-05-06 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_commission_commission_type_commission_maker_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['status', 'created_on']},
        ),
        migrations.AlterField(
            model_name='commission',
            name='status',
            field=models.CharField(choices=[('A', 'Open'), ('B', 'Full'), ('C', 'Completed'), ('D', 'Discontinued')], default='A'),
        ),
        migrations.AlterField(
            model_name='job',
            name='commission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs_needed', to='commissions.commission'),
        ),
    ]
