# Generated by Django 6.0.1 on 2026-04-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("Market Seller", "Market Seller"),
                    ("Event Organizer", "Event Organizer"),
                    ("Book Contributor", "Book Contributor"),
                    ("Project Creator", "Project Creator"),
                    ("Commission Maker", "Commission Maker"),
                    ("User", "User"),
                ],
                default="User",
                max_length=255,
            ),
        ),
    ]
