# Generated by Django 6.0.3 on 2026-05-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("User", "User"),
                    ("Market Seller", "Market Seller"),
                    ("Event Organizer", "Event Organizer"),
                    ("Book Contributor", "Book Contributor"),
                    ("Project Creator", "Project Creator"),
                    ("Commission Maker", "Commission Maker"),
                ],
                default="User",
                max_length=255,
            ),
        ),
    ]
