# Generated by Django 6.0.1 on 2026-04-19 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diyprojects", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectcategory",
            options={"ordering": ["name"], "verbose_name_plural": "Project Categories"},
        ),
    ]
